export {default as Navbar} from './navbar'
export {default as Catdetails} from './Catdetails'
export {default as Sidebar} from './Sidebar'
export {default as Gallery} from './Gallery'
export {default as Catforms} from './Catforms'
export {default as Addcatmodal} from './Addcatmodal'